<a href="https://colab.research.google.com/github/zain4cs/ML_Pipelines/blob/main/predict_without_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pickle
import numpy as np

In [ ]:
ohe_sex = pickle.load(open('/content/drive/MyDrive/Datasets/ohe_sex.pkl', 'rb'))
ohe_Embarked = pickle.load(open('/content/drive/MyDrive/Datasets/ohe_Embarked.pkl', 'rb'))
clf = pickle.load(open('/content/drive/MyDrive/Datasets/clf.pkl','rb'))

In [ ]:
# Assum User Input
# Pclass | Sex | Age	| SibSp |	Parch |	Fare |	Embarked

test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'], dtype=object).reshape(1,7)
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

______

In [ ]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
test_input_sex

array([[0., 1.]])

________________________________________

In [ ]:
test_input_Embarked  = ohe_Embarked.transform(test_input[:,-1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [ ]:
test_input_Embarked

array([[0., 0., 1., 0.]])

_______________________

In [ ]:
test_input_age = test_input[:,2].reshape(1,1)

In [ ]:
test_input_transformed = np.concatenate((test_input_age , test_input_sex , test_input_Embarked , test_input[:,[0,3,4,5]]), axis=1)

In [ ]:
test_input_transformed.shape

(1, 11)

In [ ]:
clf.predict(test_input_transformed)

array([1])